import { useEffect, useMemo, useState } from "react";
import { isTauri } from "@/lib/tauri";
import { openUrl } from "@tauri-apps/plugin-opener";
import { supabase } from "@/lib/supabase";
const URL_PART=/(https?:\/\/[^\s<]+)/gi; const URL_ONLY=/^https?:\/\/[^\s<]+$/i; const cache=new Map();
function split(value){const match=value.match(/^(.*?)([.,!?;:]+)$/);return match?{url:match[1],suffix:match[2]}:{url:value,suffix:""};}
async function openLink(url){const safe=new URL(url);if(!/^https?:$/.test(safe.protocol))throw new Error("Only web links are supported.");if(isTauri()){await openUrl(safe.href);return;}window.open(safe.href,"_blank","noopener,noreferrer");}
function LinkText({content,hidden}){return <>{content.split(URL_PART).map((part,index)=>{if(!URL_ONLY.test(part))return part;const {url,suffix}=split(part);if(url===hidden)return suffix||null;return <span key={index}><a className="v3-chat-link" href={url} target="_blank" rel="noreferrer" onClick={(event)=>{event.preventDefault();void openLink(url);}}>{url}</a>{suffix}</span>;})}</>;}
export function V3RichMessage({content,alignEnd=false}) {const url=useMemo(()=>{const first=content.match(URL_PART)?.[0];return first?split(first).url:null;},[content]);const [preview,setPreview]=useState(undefined);useEffect(()=>{if(!url)return;let disposed=false;if(cache.has(url)){setPreview(cache.get(url));return;}void supabase.functions.invoke("link-preview",{body:{url}}).then(({data,error})=>{const next=!error&&data?.preview?.title?data.preview:null;cache.set(url,next);if(!disposed)setPreview(next);}).catch(()=>{cache.set(url,null);if(!disposed)setPreview(null);});return()=>{disposed=true;};},[url]);const clickable=(event)=>{event.preventDefault();if(preview?.url)void openLink(preview.url);};return <>{content&&<p className="message-template__body"><LinkText content={content} hidden={preview?url:null}/></p>}{preview&&<a className={`v3-rich-link${alignEnd?" v3-rich-link--self":""}`} href={preview.url} target="_blank" rel="noreferrer" onClick={clickable}>{preview.image&&<img src={preview.image} alt="" referrerPolicy="no-referrer"/>}<div><strong>{preview.title}</strong>{preview.description&&<span>{preview.description}</span>}<small>{preview.siteName||new URL(preview.url).hostname}</small></div></a>}</>;}
